### ISSUE TITLE
Not a supported Inno Setup installer  - v5.5.3

### ISSUE THREAD

**Issue by Arkaop** [dscharrer/innoextract#100]
Hi,
Thanks for your nice tool, really helpful work :)

I got an old binary, which i would really like to unpack.
The binary is packed with Inno Setup install v5.5.3 (got it from ascii string, while grepin in r2).
The exe is availble at : https://app.any.run/tasks/ea8992b4-1098-430f-8f6a-e9228c743caf/
(info in the top right corner, then download)

Do you have a hint about it ?

**Comment by dscharrer** [comment]
The file has HTTP response headers prepended. If you remove them (eveything before "MZ") the file can be extracted without issues.
