### ISSUE TITLE
Can't extract single file

### ISSUE THREAD

**Issue by hgdagon** [dscharrer/innoextract#102]
I have an installer I can't extract. I know it contains cyrillic paths, but when listing, I can't see those characters, i.e

`app\_JSGME_MODS\  \gamedata\textures\ui\ui_actor_menu.dds`

So I get an error when installing

`Could not create directory "app\_JSGME_MODS\  \gamedata"`

**Comment by dscharrer** [comment]
You'll have to provide some more information? Which file are you trying to extract? Is it available to download somewhere? Which version of innoextract are you using and on which OS?

**Comment by hgdagon** [comment]
Should've kept an eye on this. Yes it's a game mod repack. It uses FreeArc archives, so I'll just upload the installer itself. FreeArc handles Cyrillic paths on its own.
[TLsetup3.zip](https://github.com/dscharrer/innoextract/files/4430652/TLsetup3.zip)

**Comment by dscharrer** [comment]
Hi, looks like this is the same bug as issue #101.

You should be able to extract the file with [development snapshot 1.9-dev-2020-01-12](https://constexpr.org/innoextract/files/snapshots/innoextract-1.9-dev-2020-01-12/):
    app/_JSGME_MODS/Исправление текстуры инвентаря/gamedata/textures/ui/ui_actor_menu.dds

**Comment by hgdagon** [comment]
Yes, it is. Thank you!
