### ISSUE TITLE
cannot extract this setup file

### ISSUE THREAD

**Issue by tahadouhi** [dscharrer/innoextract#103]
hi !
when i try to extract this setup.exe file it shows me this error :
![Capture](https://user-images.githubusercontent.com/10810222/78258336-5f238c80-74fb-11ea-8ac9-96aa231c2ca8.JPG)
link to the setup file : https://www113.zippyshare.com/v/nqIGqDXo/file.html
virustotal link : https://www.virustotal.com/gui/file/6b4d9d957814585497574958f1c4f9c879b4aa36f94ec84c0b62a063eb36e2e9/detection

**Comment by dscharrer** [comment]
I'm can't download https://www113.zippyshare.com/v/nqIGqDXo/file.html (403 Forbidden).

**Comment by tahadouhi** [comment]
> 
> 
> I'm can't download https://www113.zippyshare.com/v/nqIGqDXo/file.html (403 Forbidden).

sorry, here is the file in the attachements
[setup.zip](https://github.com/dscharrer/innoextract/files/4431726/setup.zip)

**Comment by tahadouhi** [comment]
sorry, i've reuploaded it to Google Drive:
https://drive.google.com/open?id=1g4Qe1FwE9tP0qgilOXEXcy9OYF11INlJ

**Comment by dscharrer** [comment]
This should be fixed with version 1.9.
