### ISSUE TITLE
Cannot unpack installer made with a modified Inno Setup 5.3.10

### ISSUE THREAD

**Issue by Iglu47** [dscharrer/innoextract#126]
There is the issue similar to https://github.com/dscharrer/innoextract/issues/103

![5 3 10 1](https://user-images.githubusercontent.com/25866099/144464191-f72018d3-a5e0-4322-941e-fe422ad92155.png)

I checked: the installer is available for download from several sources and they all provide the same version, as well as everything is successfully installed via Wine - the file is not corrupted.

filename: `Oceanhorn_Monster_of_Uncharted_Seas_VO_Rus.exe`
sha256sum: `25d6438b8668a90328c5f78d80631c1900429f85eb1dcffcbcee1d154817b0b7`

(This is the installer of the game modification that adds unofficial localization of the voice acting)
site: https://en.gamesvoice.ru/oceanhorn
direct-links (to the current version of the installer): [Google.Drive](https://drive.google.com/file/d/1eq39uCXUfwY5n2AWjBvtNxmnXDUQSIu-/view), [Mega.nz](https://mega.nz/#!UIRR0YBQ!tOx8SvMeu2iNWv9QJNj0m8r8bkyM4DwLYbXpVyJ2APg)

**Comment by Iglu47** [comment]
I checked: PR on current master (660546ad796bb7619ff0e99a6cd61c4e01e4e241) allows to successfully recognize and unpack the installer.
![53101m](https://user-images.githubusercontent.com/25866099/144470729-1d3eb479-a1ba-4dd2-a430-6e6d9e9adcfa.png)

**Comment by dscharrer** [comment]
Thanks for the patch.
