### ISSUE TITLE
cannot extract installer (possibly solid compressed)

### ISSUE THREAD

**Issue by crappyinstaller** [dscharrer/innoextract#129]
when i try to extract an installer, the following output appears:
```
[i enter the innoextract command with the file path]
Warning: Unexpected setup data version: 8.1.0 (unicode)
Extracting [file name] - setup data version 8.1.0 (unicode)
[extracts some files]
Opening "filename-1.bin"
 - "tmp\solidbreak" [temp]
 - "tmp\vcredist_x64.exe" [temp]
Stream error while extracting files!
 └─ error reason: inno lzma init error: iostream error
If you are sure the setup file is not corrupted, consider
filing a bug report at https://innoextract.constexpr.org/issues
Done with 1 error and 1 warning.
```

i'm pretty sure the file isn't corrupted as when i give the list argument, it returns all the contents of the .bin files and the .exe file.

also, i think that the solid compression (solidbreak file found when extracting) method used to compress the files is causing this issue. please look into it.

thanks in advance!

**Comment by dscharrer** [comment]
8.1.0 is not a valid upstream Inno Setup data version, [the latest is 6.1.0](https://github.com/jrsoftware/issrc/blob/main/Projects/Struct.pas#L36). My guess is that this is from a modified Inno Setup version. What installer gives you that error?

**Comment by pasha-zzz** [comment]
`
the latest is 6.1.0
`

6.2.1
http://jrsoftware.github.io/issrc/whatsnew.htm

**Comment by dscharrer** [comment]
Inno Setup 6.2.1 has **data** version 6.1.0 as there have been no changes to the data format since then.

Anyway, there is nothing I can do here without access to the "8.1.0" installer.
