### ISSUE TITLE
Not a supported Inno Setup installer with roller coaster tycoon 2

### ISSUE THREAD

**Issue by JombiWombi** [dscharrer/innoextract#131]
i'm on macOS and it flashes a message when i try to extract RCT2 to use with openRCT2

**Comment by dscharrer** [comment]
Which installer are you trying to extract? If you got it from GOG you need to download the offline installer (`setup\_….exe`) and not the Galaxy installer (`GOG\_Galaxy_….exe`) as the latter is not a Inno Setup installer and doesn't even contain any game data.
