### ISSUE TITLE
Multi thread support?

### ISSUE THREAD

**Issue by detectingdragon77** [dscharrer/innoextract#135]
Would it be possible to implement multi threaded extraction support?

**Comment by dscharrer** [comment]
Yes, it's planned: issue #14 

Some Inno Setup installers use solid compression (only one compression stream for all files) and those will not benefit much from multi-threading but AFAIK the most common large ones (i.e. games from GOG.com) use one compression stream per file.

**Comment by detectingdragon77** [comment]
> Yes, it's planned: issue #14
> 
> Some Inno Setup installers use solid compression (only one compression stream for all files) and those will not benefit much from multi-threading but AFAIK the most common large ones (i.e. games from GOG.com) use one compression stream per file.

Ok, sorry I didn't see #14
