### ISSUE TITLE
Cannot extract the MouseMux installer.

### ISSUE THREAD

**Issue by potatominegaming** [dscharrer/innoextract#137]
I don't know what makes it unable to extract, maybe it's the fact that it's forcefully ran as an administrator, or it's just a problem with the installer itself. I have no idea why the MouseMux installer can't be extracted with innoextract. It pops up the innoextract window, then it just... closes. It stays on screen for about 5 frames, then it disappears. Can anyone help?

**Comment by pasha-zzz** [comment]
This is Advanced Installed, not Inno Setup.

**Comment by dscharrer** [comment]
Yeah, definitely not an Inno Setup installer. Looks like Advanced Installer is MSI based so MSI extractors might work.
