### ISSUE TITLE
GOG Roller Coaster Tycoon 2 - Setup Data Version Error

### ISSUE THREAD

**Issue by ac3charland** [dscharrer/innoextract#139]
When running innoextract on the GOG offline download for Roller Coaster Tycoon 2, I'm getting the following error:
<img width="465" alt="Screenshot 2023-03-02 at 9 22 14 AM" src="https://user-images.githubusercontent.com/36909821/222471337-0c421abf-8e56-412f-a32a-21f8b9e51e92.png">
```
Command: 
innoextract setup_rollercoaster_tycoon_2_triple_thrill_pack_2.01.043_\(17987\).exe

===

Result:
Could not determine setup data version!
If you are sure the setup file is not corrupted, consider 
filing a bug report at https://innoextract.constexpr.org/issues
Done with 1 error.
```
This happens with innoextract 1.9 and 1.10-dev. Any ideas what might be going on?

OS: MacOS Ventura 13.2
Intel MacBook Pro 2018

**Comment by dscharrer** [comment]
`setup_rollercoaster_tycoon_2_triple_thrill_pack_2.01.043_(17987).exe` extracts without errors for me. Try downloading the file again and if you still get errors please post the checksum.
