### ISSUE TITLE
无法解加密的inno stupe安装包 提示

### ISSUE THREAD

**Issue by cmd1662099** [dscharrer/innoextract#146]
Warning: Unexpected setup data version: 6.1.0 (unicode)
Stream error while parsing setup headers!
 ├─ detected setup version: 6.1.0 (unicode)
 └─ error reason: block header CRC32 mismatch: iostream error
If you are sure the setup file is not corrupted, consider
filing a bug report at https://innoextract.constexpr.org/issues
Done with 1 error and 1 warning.

**Comment by dscharrer** [comment]
You need innoextract 1.9 or newer to extract that file.
