### ISSUE TITLE
Gentoo package

### ISSUE THREAD

**Issue by DarthGandalf** [dscharrer/innoextract#147]
https://constexpr.org/innoextract/ says that innoextract is available in [arx-libertatis overlay](https://github.com/arx/ArxGentoo/), but it's actually available in ::gentoo itself: https://packages.gentoo.org/packages/app-arch/innoextract

Please update the website

**Comment by dscharrer** [comment]
Thanks but I am aware of the Gentoo package.

**Comment by DarthGandalf** [comment]
Can you please update the website then to mention it? As there's no need to
add any overlay to install innoextract

чт, 8 июн. 2023 г., 11:55 Daniel Scharrer ***@***.***>:
