### ISSUE TITLE
Arm64 Linux build?

### ISSUE THREAD

**Issue by Shivansps** [dscharrer/innoextract#155]
Ive been trying to get a arm64 binary, i did try to compile it myseldt but i get errors pointing to undefined references to iostream/zlib/bzip2. Any way to get a compile bin with the same configuration with the one that is used for the official builds that only seems to need 4 dynamic libs?

**Comment by dscharrer** [comment]
You need to statically those libraries if you want a portable binary. Make sure static versions of those dependencies (.a files) are available in your build root and then configure the innoextract build with `-DUSE_STATIC_LIBS=1`.

**Comment by Shivansps** [comment]
> You need to statically those libraries if you want a portable binary. Make sure static versions of those dependencies (.a files) are available in your build root and then configure the innoextract build with `-DUSE_STATIC_LIBS=1`.

The problem is that when i compile it with no arguments exactly like it is in the instructions i end up with a dynamic linked 12.8MB bin.

When i try to use -DUSE_STATIC_LIBS=1 or with -DLZMA_USE_STATIC_LIBS=1 -DBoost_USE_STATIC_LIBS=1 -DZLIB_USE_STATIC_LIBS=1 -DBZip2_USE_STATIC_LIBS=1 -Diconv_USE_STATIC_LIBS=1 it fails at linking:

`
100%] Linking CXX executable innoextract
lto-wrapper: warning: using serial compilation of 9 LTRANS jobs
/usr/lib/aarch64-linux-gnu/libboost_iostreams.a(bzip2.o):function boost::iostreams::detail::bzip2_base::end(bool, std::nothrow_t): error: undefined reference to 'BZ2_bzCompressEnd'
/usr/lib/aarch64-linux-gnu/libboost_iostreams.a(bzip2.o):function boost::iostreams::detail::bzip2_base::end(bool, std::nothrow_t): error: undefined reference to 'BZ2_bzDecompressEnd'
/usr/lib/aarch64-linux-gnu/libboost_iostreams.a(bzip2.o):function boost::iostreams::detail::bzip2_base::compress(int): error: undefined reference to 'BZ2_bzCompress'
/usr/lib/aarch64-linux-gnu/libboost_iostreams.a(bzip2.o):function boost::iostreams::detail::bzip2_base::decompress(): error: undefined reference to 'BZ2_bzDecompress'
/usr/lib/aarch64-linux-gnu/libboost_iostreams.a(bzip2.o):function boost::iostreams::detail::bzip2_base::end(bool): error: undefined reference to 'BZ2_bzDecompressEnd'
/usr/lib/aarch64-linux-gnu/libboost_iostreams.a(bzip2.o):function boost::iostreams::detail::bzip2_base::end(bool): error: undefined reference to 'BZ2_bzCompressEnd'
/usr/lib/aarch64-linux-gnu/libboost_iostreams.a(bzip2.o):function boost::iostreams::detail::bzip2_base::do_init(bool, void* (*)(void*, int, int), void (*)(void*, void*), void*): error: undefined reference to 'BZ2_bzCompressInit'
/usr/lib/aarch64-linux-gnu/libboost_iostreams.a(bzip2.o):function boost::iostreams::detail::bzip2_base::do_init(bool, void* (*)(void*, int, int), void (*)(void*, void*), void*): error: undefined reference to 'BZ2_bzDecompressInit'
/usr/lib/aarch64-linux-gnu/libboost_iostreams.a(zlib.o):function boost::iostreams::detail::zlib_base::after(char const*&, char*&, bool): error: undefined reference to 'crc32'
/usr/lib/aarch64-linux-gnu/libboost_iostreams.a(zlib.o):function boost::iostreams::detail::zlib_base::xdeflate(int): error: undefined reference to 'deflate'
/usr/lib/aarch64-linux-gnu/libboost_iostreams.a(zlib.o):function boost::iostreams::detail::zlib_base::xinflate(int): error: undefined reference to 'inflate'
/usr/lib/aarch64-linux-gnu/libboost_iostreams.a(zlib.o):function boost::iostreams::detail::zlib_base::reset(bool, bool): error: undefined reference to 'deflateReset'
/usr/lib/aarch64-linux-gnu/libboost_iostreams.a(zlib.o):function boost::iostreams::detail::zlib_base::reset(bool, bool): error: undefined reference to 'inflateEnd'
/usr/lib/aarch64-linux-gnu/libboost_iostreams.a(zlib.o):function boost::iostreams::detail::zlib_base::reset(bool, bool): error: undefined reference to 'deflateEnd'
/usr/lib/aarch64-linux-gnu/libboost_iostreams.a(zlib.o):function boost::iostreams::detail::zlib_base::reset(bool, bool): error: undefined reference to 'inflateReset'
/usr/lib/aarch64-linux-gnu/libboost_iostreams.a(zlib.o):function boost::iostreams::detail::zlib_base::do_init(boost::iostreams::zlib_params const&, bool, void* (*)(void*, unsigned int, unsigned int), void (*)(void*, void*), void*): error: undefined reference to 'deflateInit2_'
/usr/lib/aarch64-linux-gnu/libboost_iostreams.a(zlib.o):function boost::iostreams::detail::zlib_base::do_init(boost::iostreams::zlib_params const&, bool, void* (*)(void*, unsigned int, unsigned int), void (*)(void*, void*), void*): error: undefined reference to 'inflateInit2_'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/innoextract.dir/build.make:834: innoextract] Error 1
make[1]: *** [CMakeFiles/Makefile2:112: CMakeFiles/innoextract.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
`
I suspect that libboost-iostreams-dev from the repo is not compiled with bzip and zlib support.

Also what about the filesize? I want something like the ones that are on release that are about 900kb that i belive are compiled with these arguments -DLZMA_USE_STATIC_LIBS=1 -DBoost_USE_STATIC_LIBS=1 -DZLIB_USE_STATIC_LIBS=1 -DBZip2_USE_STATIC_LIBS=1 -Diconv_USE_STATIC_LIBS=1

**Comment by Shivansps** [comment]
UPDATE:
After starting with a clean system, instead of installing libboost-all-dev i just compiled it from source that enabled bzip2 and zlib support. That fixed the compile error.

As for the file size i had to use -DFASTLINK=1 that still produced a 2.9MB file (14MB whiout it) while also running -DUSE_STATIC_LIBS=1 not sure if im missing something more here. 

root@orangepi5:~/innoextract/build# ldd ./innoextract
        linux-vdso.so.1 (0x0000ffffad5de000)
        libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000ffffad2d0000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffffad120000)
        /lib/ld-linux-aarch64.so.1 (0x0000ffffad5a1000)
root@orangepi5:~/innoextract/build# ls -lh innoextract
-rwxr-xr-x 1 root root 2.9M Aug 27 22:02 innoextract
