### ISSUE TITLE
Add support for RC4-encrypted installers

### ISSUE THREAD

**Issue by dscharrer** [dscharrer/innoextract#31]
Unless someone provides me with an encrypted installer, this will be low priority. Its here mostly for completeness.

**Comment by kholia** [comment]
@dscharrer https://github.com/kholia/inno2john/tree/tweaks-v1/samples/Output

The password is "openwall".

**Comment by dscharrer** [comment]
Thanks, i'll look into it when I have time.

**Comment by dscharrer** [comment]
This has been implemented for innoextract 1.7 (to be released soon), a [release candidate](http://constexpr.org/innoextract/files/snapshots/innoextract-1.7-rc1/) is available for testing.

Additionally, there is also a `--show-password` option to print the password checksum and salt.
