### ISSUE TITLE
Cannot build on CentOS

### ISSUE THREAD

**Issue by ReklatsMasters** [dscharrer/innoextract#39]
I'm use centos 6. Boost has version 1.41 and name like libboost_system-mt.so. But linker need libboost_system-mt**-shared**.so. When make i symlink,
```bash
ln -s /usr/lib/libboost_system-mt.so /usr/lib/libboost_system-mt-shared.so
```
then make don`t work
```bash
make
...
make[2]: *** No rule to make target `/usr/lib/lib/libboost_iostreams-mt.so.5', needed by `innoextract'.  Stop.
make[1]: *** [CMakeFiles/innoextract.dir/all] Error 2
make: *** [all] Error 2
```

:dizzy_face:

**Comment by dscharrer** [comment]
Hi,

it looks like the [boost-devel package in CentOS 6 ships with a broken cmake config](http://www.cmake.org/Bug/view.php?id=15270). However that config isn't actually needed at all - you can tell cmake to ignore that config by passing `-DBoost_NO_BOOST_CMAKE=1`:

    cmake .. -DBoost_NO_BOOST_CMAKE=1

Let me know if that works for you.

**Comment by ReklatsMasters** [comment]
Thanx! It's work!
