### ISSUE TITLE
Cmake configure error on windows.

### ISSUE THREAD

**Issue by luckcolors** [dscharrer/innoextract#42]
Hello.
I'm trying to compile innoextract on windows i tried both without cygwin and with cygwin
(with dependencies installed from the installer)
But both fail with the same error:

Luckcolors@Luckcolors-PC ~/innoextract
$ mkdir -p build && cd build && cmake ..
-- Building for: Visual Studio 12 2013
-- The C compiler identification is MSVC 18.0.31101.0
-- The CXX compiler identification is MSVC 18.0.31101.0
-- Check for working C compiler using: Visual Studio 12 2013
-- Check for working C compiler using: Visual Studio 12 2013 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler using: Visual Studio 12 2013
-- Check for working CXX compiler using: Visual Studio 12 2013 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
-- Found PythonInterp: D:/cygwin64/bin/python (found version "1.4")
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.1/Modules/FindPackageH
andleStandardArgs.cmake:138 (message):
  Could NOT find LZMA (missing: LZMA_LIBRARY LZMA_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.1/Modules/FindPackageHandleStandard
Args.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLZMA.cmake:74 (find_package_handle_standard_args)
  CMakeLists.txt:102 (find_package)

-- Configuring incomplete, errors occurred!
See also "D:/cygwin64/home/Luckcolors/innoextract/build/CMakeFiles/CMakeOutput.l
og".

**Comment by dscharrer** [comment]
You need to download (or compile) [libllvm](http://tukaani.org/xz/) and [Boost](http://sourceforge.net/projects/boost/files/boost-binaries/1.58.0/) libraries and then tell CMake where to find them.

Use `CMAKE_INCLUDE_PATH` to point to where the includes can be found and `CMAKE_LIBRARY_PATH` for the libraries. These can be either set as environment variables or passed to `cmake` on the command line via the `-D<var>=<value>` syntax. For multiple paths separate them using `;`.

There are pre-built innoextract binaries for Windows at http://constexpr.org/innoextract/#download - if these don't work for you consider filing a bug for that.

**Comment by luckcolors** [comment]
yeah these doesn't work for innosetup 5.5.5

**Comment by luckcolors** [comment]
there's no libllvm on http://tukaani.org/xz/ are you sure that is the correct link?

**Comment by dscharrer** [comment]
I'm sorry, I meant liblzma. It's part of the xz-utils package.

**Comment by dscharrer** [comment]
> yeah these doesn't work for innosetup 5.5.5

Yes they do, even if the `--version` output says differently - the Inno Setup data format has not changed since 5.5.0. Is there any specific installer you are having problems with? Can you post the full innoextract output?

**Comment by luckcolors** [comment]
ah ok.
Here's the error:

warning: unexpected data while converting from CP1200 to UTF-8
stream error: basic_ios::clear
Done with 1 error and 1 warning.

**Comment by dscharrer** [comment]
Ah, not much to go on with just the error message :(

What installer are you trying to extract?

**Comment by luckcolors** [comment]
sent you the setup.

**Comment by dscharrer** [comment]
Thanks. I can reproduce the error here, even with git master. Will look into it.

> Inno Setup Setup Data (5.5.0) (u)...............................Inno Setup Messages (5.5.0) (u)

That is just the data version / messages data version - it could be made using any 5.5.x version.

**Comment by luckcolors** [comment]
Ok thanks :)
