### ISSUE TITLE
can not extract vapoursynth-r28.exe 

### ISSUE THREAD

**Issue by retsyo** [dscharrer/innoextract#46]
vapoursynth-r28.exe is found on https://github.com/vapoursynth/vapoursynth/releases

    innoextract.exe vapoursynth-r28.exe
    Extracting "VapourSynth R28" - setup data version 5.5.6 (unicode)
     - "sys\vsvfw.dll" (0.01e-009 KiB) - overwritten
     - "sys\vsscript.dll" (1.Fe-009 KiB) - overwritten
     - "app\plugins32\"
     - "app\plugins64\"
    Could not create directory "code:GetPythonPath32"
    Done with 1 error.

**Comment by dscharrer** [comment]
Related to issue #32. Windows does not like some special characters in filenames.

**Comment by dscharrer** [comment]
This has been fixed in innoextract 1.6.
