### ISSUE TITLE
InnoExtract crash

### ISSUE THREAD

**Issue by lovebdsobuj** [dscharrer/innoextract#47]
After command ```innoextract setup.exe```
It's start extracting... But few files extract and it gotten force close. 

setup data version: 5.5.0.1
setup.exe file size: 90MB+
![screenshot_00059_20h24m47s](https://cloud.githubusercontent.com/assets/10352682/11767461/785a4d2e-a1d8-11e5-85f2-ecaf517f3557.png)

**Comment by dscharrer** [comment]
Hi,

What innoextract version do you experience this with?

Can you provide the setup file that causes this crash? If not, please generate a minidump: In the Task Manager find the `innoextract` process, right click it and select "Create dump file". Then upload the created file somewhere and link it here or send it to me: daniel@constexpr.org

**Comment by lovebdsobuj** [comment]
Hello, 
Thanks for your ASAP reply. 

Im using ```InnoExtract``` latest 1.5 version.
OS: Windows 10

Im trying to Extracting ```Demo Builder``` setup file.

Here is my InnoExtract.DMP Minidump File Summary -
https://gist.github.com/lovebdsobuj/e5b0d4a0f15f28d47926

**Comment by dscharrer** [comment]
Please attach the actual (binary) .dmp file. Also wait for innoextract to crash before creating the dump file.

**Comment by lovebdsobuj** [comment]
It's a long size file upto 55mb+, it's important...?

**Comment by lovebdsobuj** [comment]
Can't extract the http://www.demo-builder.com/dbsetup_trial.exe file. 
Sir, please can you ensure me this problem just for me, or also you....

**Comment by dscharrer** [comment]
> http://www.demo-builder.com/dbsetup_trial.exe

I can extract that file under Linux and Windows 7 without problems.

**Comment by dscharrer** [comment]
> It's a long size file upto 55mb+, it's important...?

That is lager than I had hoped - it seems Task Manager creates full memory minidumps :/

You could try creating the minidump using another tool like Process Explorer.

I will need either a minidump or a way to reproduce the problem in order to be able to fix it.

**Comment by dscharrer** [comment]
I have found an issue in my build setup resulted in the compiler adding AVX instructions to the release binaries, resulting in crashes on Windows XP and systems with older processors.

Please try this updated build and let me know if there are still any issues:
 http://constexpr.org/innoextract/files/snapshots/innoextract-1.6-rc1-windows.zip

Particularly, let me know if
- it still crashes
- the file sizes in the output are messed up

Thanks.

**Comment by lovebdsobuj** [comment]
@dscharrer Wow!

Fantastic work!

Extract completed successfully... Without no bugs!

You can make it stable version.

Thanks for your awesome work.

**Comment by dscharrer** [comment]
This has been fixed in innoextract 1.6.
