### ISSUE TITLE
ubuntu 15.10 / GCC 5.2 fix

### ISSUE THREAD

**Issue by digitalist** [dscharrer/innoextract#49]
* default packaged version (apt-get install innoextract) does not work because of boost linker errors
* compile from source does not work because you need to add this line to CMakeLists.txt:
*add_definitions(-D_GLIBCXX_USE_CXX11_ABI=0)*
this can be a problem of my setup, but in any case, it can help someone

**Comment by dscharrer** [comment]
On a new install of Ubuntu 15.10 both innoextract packages (distro repo and ppa) work out of the box for me. I can also build innoextract from source on that install without any additional flags. Did you manually install a different Boost or GCC version?

**Comment by digitalist** [comment]
i guess so, that's why 'it can be a problem of my setup' sorry for troubling you

**Comment by dscharrer** [comment]
No worries, might still be a good idea to add `-D_GLIBCXX_USE_CXX11_ABI=0` automatically if boost was compiled that way - I'll look into it.

**Comment by dscharrer** [comment]
I have decided it's not worth it automatically adding `-D_GLIBCXX_USE_CXX11_ABI=0` when Boost was compiled with a setting different from the current compiler's default.
