### ISSUE TITLE
OSX: "Segmentation fault: 11"

### ISSUE THREAD

**Issue by oboewan42** [dscharrer/innoextract#51]
Running OSX 10.11.3, with innoextract installed via Homebrew. Attempting to use it to extract the RollerCoaster Tycoon 2 installer from GOG (setup_rollercoaster_tycoon2_2.0.0.6.exe) results in "Segmentation fault: 11".

EDIT: Works fine when built from source, appears to be a Homebrew-related issue

**Comment by dscharrer** [comment]
Thanks for the report, but as I don't have access to a mac there isn't anything I can do here. Have you reported the issue to the Homebrew maintainers?

**Comment by shrx** [comment]
@oboewan42 can you describe how to build from source? I tried it but I get errors when trying to extract:
```
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicudata.56.1.dylib
  Referenced from: /usr/local/opt/boost/lib/libboost_regex-mt.dylib
  Reason: image not found
Trace/BPT trap: 5
```
