### ISSUE TITLE
then how to put it back again?

### ISSUE THREAD

**Issue by Dj-jom2x** [dscharrer/innoextract#52]
then how to put it back again? in one piece ?

**Comment by dscharrer** [comment]
`innoextract` only supports extracting the files from an Inno Setup installer - changing installers or creating new ones is out of scope of the project.

Currently innoextract does not extract the metadata necessary to re-create installer using the Inno Setup tools, but [innounp](http://innounp.sourceforge.net/) does (at least to some extend). See [this article](https://webcache.googleusercontent.com/search?q=cache:ZEsmHmWFQsoJ:https://coolaj86.com/articles/how-to-unpackage-and-repackage-an-innosetup-exe.html+&cd=4&hl=en&ct=clnk&gl=us) on how to do it.

**Comment by Dj-jom2x** [comment]
yeah i already did that i will use it for my cracks XD so i don't need to
create patcher ...
