### ISSUE TITLE
Unexpected setup data version with arc compression

### ISSUE THREAD

**Issue by mirh** [dscharrer/innoextract#54]
http://freearc.org/InnoSetup.aspx
I'd gladaly even link the alleged faulty setup, but it's a 4GB torrent.

**Comment by dscharrer** [comment]
The Inno Setup free arc support you linked just extracts arc archived stored inside the Inno Setup installer or shipped alongside it (possibly renamed to .bin). You should be able to extract those files with unarc without special support in `innoextract`. I'm not going to investigate the installer itself without a legal way to acquire it.
