### ISSUE TITLE
Add support for reassembling GOG Galaxy file parts

### ISSUE THREAD

**Issue by JayAndCatchFire** [dscharrer/innoextract#58]
When I try to extract the files from GOG's "Unreal 2 - The Awakening Special Edition" installer, there are no errors or anything like that.  However, the `app` directory is mostly empty.  There's a `commonappdata` folder that I don't recall having seen with any of the other GOG installers.  And most of the data is in the `tmp` directory, but broken up into very small pieces that appear to be parts of larger files that are addressed by hashes.

Here's [a link to my output](https://gist.github.com/JayAndCatchFire/0253689ff3fed7e6f118625f69e7d7d5) from just listing the contents of the installer.  I would include it here, but it's too long for the body of a GitHub issue.

It's very bizarre and completely unusable.  Any ideas as to what may be going on here?

**Comment by dscharrer** [comment]
Support for GOG Galaxy files has been added to innoextract 1.7 (to be released soon), a [release candidate](http://constexpr.org/innoextract/files/snapshots/innoextract-1.7-rc1/) is available for testing.

Current limitations:
- Architecture and OS constraints are ignored (language constraints are supported and there is a warning for non-default architecture and OS constraints) - are these used anywhere?
- All parts of the same file must have the same constraints (there is a warning for this also the first part contains a checksum for the whole file so this is likely OK)

Current advantages over [`gogextract`](https://github.com/immi101/innoextract/tree/gogextract):
- GOG Galaxy files are handled without the `--gog` option for installers published by GOG.com (the `--gog` option still forces it for all installers)
- Dependencies (ie before_install_dependency/after_install_dependency) are also extracted
- Collisions (overwriting/renaming) works correctly for multi-part files
- GOG Galaxy language constraints are handled via the `--language`and `--language-only` options just like normal Inno Setup language constraints
- `--list-languages` lists languages used in GOG Galaxy constraints
- The re-assembled file is validated against the file checksum
- The output file is opened only once for multi-part files
