### ISSUE TITLE
Improve handling of duplicate files

### ISSUE THREAD

**Issue by dscharrer** [dscharrer/innoextract#6]
Inno Setup installers can contain multiple files with the same name (for different languages/setup options/...).

Currently they are all extracted to the same location, each file overwriting the previous one. The only option to get a specific variant is the --language option.

innounp has the following option:

    -a     process all copies of duplicate files

We should also have something like that and then automatically give the files unique names (maybe like "filename@en", "filename@de", ...?)

Something like --overwrite=ask|rename|clobber where clobber is the current behavior and rename is the proposed one (maybe the future default).

One concern is how this would interact when selecting specific components/languages/...: it's not really intuitive when extracting only component a gives file "file" but extracting all components only gives "file@a", "file@b", ....

**Comment by a-detiste** [comment]
> filename@en 

I guess english should be special-cased to be the *default*, in a way only other language got renamed.

https://github.com/dscharrer/innoextract/pull/44

**Comment by dscharrer** [comment]
1.5 as the `--collisions=rename` option
