### ISSUE TITLE
Error with gimp-2.10.2-setup.exe

### ISSUE THREAD

**Issue by marcoratto** [dscharrer/innoextract#60]
Hi,
I have this error:
**innoextract.exe -t gimp-2.10.2-setup.exe**
Stream error while parsing setup headers!
 ├─ detected setup version: 5.5.7 (unicode)
 └─ error reason: basic_ios::clear
If you are sure the setup file is not corrupted, consider
filing a bug report at http://innoextract.constexpr.org/issues
Done with 1 error.

How can I solve it ?

**Comment by marcoratto** [comment]
Add the following info:

innoextract.exe -v
innoextract 1.6
Extracts installers created by Inno Setup 1.2.10 to 5.5.8

**Comment by dscharrer** [comment]
gimp-2.10.2-setup.exe seems to use a setup based on a pre-relase version of Inno Setup 5.6.0. Unfortunately the data version hasn't been bumped but we should still be able to detect this.

**Comment by dscharrer** [comment]
This should be fixed with innoextract 1.7 (to be released soon), a [release candidate](http://constexpr.org/innoextract/files/snapshots/innoextract-1.7-rc1/) is available for testing.
