### ISSUE TITLE
Myst: Masterpiece Edition from GOG extracts with missing files

### ISSUE THREAD

**Issue by Mister-Dolus** [dscharrer/innoextract#61]
No error message shows in the terminal, but most of the files in the QTW directory are missing whenever I try to extract the game. I'm certain this installer if fine since it had all the needed files for ScummVM when I installed it via Wine. 

OS: Ubuntu Mate 18.04

**Comment by dscharrer** [comment]
Please post the full terminal output.

**Comment by dscharrer** [comment]
Assuming this is a duplicate of issue #58 until further information is provided.
