### ISSUE TITLE
Multilanguage Windows installer

### ISSUE THREAD

**Issue by bovirus** [dscharrer/innoextract#64]
Can I help you about the Windows installer to make it multi-langauge?
Where can i find the iss Inno Setup Script for the installer?

**Comment by dscharrer** [comment]
innoextract does not have a Windows installer - it comes as a zip file with a portable `innoextract.exe`, there is nothing to install.

**Comment by bovirus** [comment]
Thanks. Sorry for the error.

**Comment by dscharrer** [comment]
No worries.
