### ISSUE TITLE
Inno Setup 5.5.7 u(nicode) error

### ISSUE THREAD

**Issue by clrblind** [dscharrer/innoextract#66]
Hi. I have installer maded with Inno Setup 5.5.7 u. And I got error when trying to unpack or get information about installer.
[SetupCryptoSocket081217.zip](https://github.com/dscharrer/innoextract/files/2143665/SetupCryptoSocket081217.zip)

**Comment by dscharrer** [comment]
Hi, I've added support for this to the development code.

You con try [today's development snapshot](http://constexpr.org/innoextract/files/snapshots/innoextract-1.8-dev-2018-06-28/) to see if everything works for you.

**Comment by clrblind** [comment]
Thank you very much! Works fine!
