### ISSUE TITLE
File access API / Virtual File System

### ISSUE THREAD

**Issue by vdisasm** [dscharrer/innoextract#67]
Hi,

I'm working on project to decompile ``CompiledCode.bin`` one day ( https://vdisasm.com/#isd).

And I need reliable way to unpack compiledCode.bin file. Now I use InnoUnpack.exe, but your project seems could fit better.

Best solution I can imagine is Virtual File System APIs to list contents of archive, including embedded data (compiledCode is one of such data).

So I could use your project as a  DLL, list files, pick one needed and call some ``ExtractToMemory(path)`` function.

Or at least extract CompiledCode.bin only.

**Comment by dscharrer** [comment]
A library mode for innoextract is unlikely to be added soon but an option to extract the pascal script byte code should be possible..

**Comment by vdisasm** [comment]
ok, thanks
