### ISSUE TITLE
bad chunk magic: iostream error on armhf

### ISSUE THREAD

**Issue by emorrp1** [dscharrer/innoextract#68]
Hi, I was only able to extract this particular archive on my main machine (amd64), not on the pi (armhf). I got the same results with v1.7 and I am able to extract other archives on the pi without issue.

I'm guessing this is an upstream issue (found on [Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=903312)), but I don't know what else to provide for diagnosis, given it's commercial data. I checked the obvious things like md5sum, fresh download, free space etc.

```
$ innoextract --version
innoextract 1.6
Extracts installers created by Inno Setup 1.2.10 to 5.5.8
$ innoextract --test setup_anno_1404_gold_edition_2.01.5010_\(13111\).exe
Testing "Anno 1404" - setup data version 5.5.7 (unicode)
 - "tmp/DirectXEULA.txt" [temp] (9.92 KiB) - overwritten
 - "tmp/MSVC2005EULA.txt" [temp] (5 KiB) - overwritten
 - "tmp/EULA.txt" [temp] (46.2 KiB) - overwritten
 - "app/goggame-1440426004.ico" (134 KiB) - overwritten
Opening "setup_anno_1404_gold_edition_2.01.5010_(13111)-1.bin"
Stream error while extracting files!
 └─ error reason: bad chunk magic: iostream error
If you are sure the setup file is not corrupted, consider 
filing a bug report at http://innoextract.constexpr.org/issues
Done with 1 error.
```

**Comment by dscharrer** [comment]
This has been fixed in the [latest development snapshot](http://constexpr.org/innoextract/files/snapshots/innoextract-1.8-dev-2018-09-09/).
