### ISSUE TITLE
Extract file with full path

### ISSUE THREAD

**Issue by marcoratto** [dscharrer/innoextract#69]
Hi,
I'm trying to extract the following file:
http://www.prezziarionazionale.it/sw/Fmr_ComputoNaz.exe

I have the following error:
c:\innoextract-1.7-windows\innoextract.exe -e -d Fmr_ComputoNaz.exe_FILES Fmr_ComputoNaz.exe
Extracting "Computo Nazionale 02.06.2018" - setup data version 5.5.6
Could not create directory "Fmr_ComputoNaz.exe_FILES\c:"
Done with 1 error.

I think the problem is because there is an absolute path inside the EXE setup file:

innoextract-1.7-windows\innoextract.exe -t Fmr_ComputoNaz.exe
Testing "Computo Nazionale 02.06.2018" - setup data version 5.5.6
 - "tmp\isxdl.dll" [temp]
 - "dao\dao360.dll"
 - "app\dynapdf.dll"
 - "app\StrStorage.dll"
 - "app\LogoFmr.tif"
 - "app\Fmr.mdw"
 - "app\FmrNaz.ico"
 - "app\Skeylink.dll"
 - "app\COMPUTOPN.MDE"
 - "app\tccnz000.tar"
 - "app\esempiofree.cmp"
 **- "c:\fmr\manuali\cmpnazhlp.pdf"**
 - "sys\XBS200.DLL"
 - "app\InetTransferLib.mde"
 - "app\funzioni.dat"
Done.

How can I solve the problem using a target folder ?

I used the following workaround:
innoextract-1.7-windows\innoextract.exe -e Fmr_ComputoNaz.exe
Extracting "Computo Nazionale 02.06.2018" - setup data version 5.5.6
 - "tmp\isxdl.dll" [temp]
 - "dao\dao360.dll"
 - "app\dynapdf.dll"
 - "app\StrStorage.dll"
 - "app\LogoFmr.tif"
 - "app\Fmr.mdw"
 - "app\FmrNaz.ico"
 - "app\Skeylink.dll"
 - "app\COMPUTOPN.MDE"
 - "app\tccnz000.tar"
 - "app\esempiofree.cmp"
 - "c:\fmr\manuali\cmpnazhlp.pdf"
 - "sys\XBS200.DLL"
 - "app\InetTransferLib.mde"
 - "app\funzioni.dat"
Done.

**Comment by dscharrer** [comment]
This has been fixed in the [latest development snapshot](http://constexpr.org/innoextract/files/snapshots/innoextract-1.8-dev-2018-09-09/).
