### ISSUE TITLE
Extract installers creted with "Custom Installer Ultimate"

### ISSUE THREAD

**Issue by kassane** [dscharrer/innoextract#71]
Would it be possible to extract configuration files from this type of installer?
[Protected Setup](https://fileforums.com/showthread.php?t=99345)

**Comment by dscharrer** [comment]
Is the file available somewhere that doesn't require signup? Any example setup files?

**Comment by dscharrer** [comment]
Also this seems to be just an innoextract script or did they also mod the setup executables? What goes wrong when you try to extract them with the latest `innoextract` release?

**Comment by kassane** [comment]
This project generates an encrypted compilation in the installer including the extracted script.
[Download files](https://drive.google.com/drive/folders/1tOLSw1zmY7c4xNfCyILWEHCwxcHRDLyN?usp=sharing)

**Comment by dscharrer** [comment]
Without the setup file in question, there is nothing I can do here.
