### ISSUE TITLE
failed to unpack Inno Setup 5.6.1 installer

### ISSUE THREAD

**Issue by DavidXanatos** [dscharrer/innoextract#72]
Trying to unpack this setup: https://www.majorgeeks.com/files/details/stopwinupdates.html
wails with an error:

'''
F:\T\innoextract-1.7-windows>innoextract.exe "StopWinUpdates v2.3.exe"
Warning: Unexpected setup data version: 5.5.7
Warning: Unexpected Uninstall Log Mode value: 97
Warning: Unexpected Privileges value: 110
Warning: Unexpected Language Detection value: 105
Warning: Unexpected Architecture flags: 70
Warning: Unexpected Auto Boolean value: 104
Warning: Unexpected Uninstall Log Mode value: 97
Warning: Unexpected Privileges value: 110
Warning: Unexpected Language Detection value: 105
Warning: Unexpected Architecture flags: 60
Warning: Unexpected Auto Boolean value: 104
Stream error while parsing setup headers!
 ├─ detected setup version: 5.5.7
 └─ error reason: basic_ios::clear
If you are sure the setup file is not corrupted, consider
filing a bug report at http://innoextract.constexpr.org/issues
Done with 1 error and 11 warnings.
'''

**Comment by dscharrer** [comment]
This has been fixed in the [latest development snapshot](http://constexpr.org/innoextract/files/snapshots/innoextract-1.8-dev-2018-09-09/).
