### ISSUE TITLE
Add support for modified Inno Setup 5.5.7

### ISSUE THREAD

**Issue by ExaFlop1** [dscharrer/innoextract#73]
> innoextract.exe -e "M:\Repair\FonePaw.iPhone.Data.Recovery\iphone-data recovery.exe" -d "M:\Repair\FonePaw.iPhone.Data.Recovery\temp" -m -s 
Stream error while parsing setup headers!
- detected setup  version:  5.5.7  (Unicode)
- error reason: basic_ios::clear
<— error reason: basic_ios::clear
If you are sure the setup file is not corrupted, consider
filing a bug report at http://innoextract.constexpr.org/issues
Done with 1 error.

>

**Comment by dscharrer** [comment]
Duplicate of issue #68. This has been fixed in the [latest development snapshot](http://constexpr.org/innoextract/files/snapshots/innoextract-1.8-dev-2018-09-09/). Let me know if you still have any issues with that version.

**Comment by jonathanlinat** [comment]
Same here. Last version.

![image](https://user-images.githubusercontent.com/14064112/47216863-c20f7b00-d37c-11e8-843a-338e0c041904.png)

**Comment by dscharrer** [comment]
@jonathanlinat That is most likely a different issue and already fixed in the [latest development snapshot](http://constexpr.org/innoextract/files/snapshots/).

**Comment by jonathanlinat** [comment]
Tried 1.8 and worked. 👍

**Comment by dscharrer** [comment]
The installer in question is a modified installer with an incompatible data format but unchanged version number. I have done some preliminary RE and am able to extract the files but don't fully understand the headers yet.

**Comment by vv221** [comment]
Since commit https://github.com/dscharrer/innoextract/commit/d2f400f98b1208268937ec7983ef09d9d423cb18 fixed this issue, should it not be closed?

**Comment by dscharrer** [comment]
innoextract 1.8 has been released with support for a number of modified installers.
