### ISSUE TITLE
5.6.2 support for GOG?

### ISSUE THREAD

**Issue by Shionsan** [dscharrer/innoextract#74]
```
Warning: Unexpected setup data version: 5.6.2 (unicode)
Warning: Unexpected Auto Boolean value: 19
Warning: Unexpected Auto Boolean value: 20
Warning: Unexpected trailing byte in UTF-16 string.
Warning: Unexpected data while converting from UTF-16LE to UTF-8.
Warning: Unexpected trailing byte in UTF-16 string.
Warning: Unexpected data while converting from UTF-16LE to UTF-8.
Warning: Unexpected data while converting from UTF-16LE to UTF-8.
Stream error while parsing setup headers!
 ├─ detected setup version: 5.6.2 (unicode)
 └─ error reason: basic_ios::clear
If you are sure the setup file is not corrupted, consider
filing a bug report at http://innoextract.constexpr.org/issues
Done with 1 error and 8 warnings.
```

**Comment by dscharrer** [comment]
This should already work with the [latest development snapshot](http://constexpr.org/innoextract/files/snapshots/), can you test that?

**Comment by Shionsan** [comment]
innoextract-1.8-dev-2018-09-09-windows.zip - seems to be able to unpack latest GOG files. Thanks!

It still shows the version warning though:
`Warning: Unexpected setup data version: 5.6.2 (unicode)`

**Comment by dscharrer** [comment]
Yes, Inno Setup 5.6.2 hasn't been released yet and the final data format might still change. Unfortunate that GOG is using a development version.

**Comment by Malvineous** [comment]
Thanks for this - just confirming that a 5.6.2 GOG download gave me the same error with the latest innoextract release, but the git version worked fine with the same single version number warning.

**Comment by dscharrer** [comment]
Looks like there was a regression with the 5.6.2 support.
