### ISSUE TITLE
"Could not verify output checksum" in ostensibly valid files

### ISSUE THREAD

**Issue by ssokolow** [dscharrer/innoextract#81]
While using `innoextract -t --gog` with innoextract 1.8-dev + 38ae68f to double-check a bunch of files I downloaded using LGOGDownloader, I ran across this set of warnings:

```
Testing "The Incredible Adventures of Van Helsing - Final Cut" - setup data version 5.6.2 (unicode)
Opening "the_incredible_adventures_of_van_helsing_final_cut_game/setup_the_incredible_adventures_of_van_helsing_-_final_cut_1.1.0b_(b)_(23988)-1.bin"
[...]
Opening "the_incredible_adventures_of_van_helsing_final_cut_game/setup_the_incredible_adventures_of_van_helsing_-_final_cut_1.1.0b_(b)_(23988)-2.bin"
[...]
Warning: Could not verify output checksum of file Terrains/csatorna_tudos/medium/Files.N2PK
[...]
Warning: Could not verify output checksum of file Terrains/driad_boss_arena/medium/Files.N2PK
[...]
Opening "the_incredible_adventures_of_van_helsing_final_cut_game/setup_the_incredible_adventures_of_van_helsing_-_final_cut_1.1.0b_(b)_(23988)-3.bin"
[...]
Warning: Could not verify output checksum of file Terrains/Gorge_of_Eternal_Peril/medium/Files.N2PK
[...]
Warning: Could not verify output checksum of file Terrains/Ink_tukor_varos/Files.N2PK
[...]
Opening "the_incredible_adventures_of_van_helsing_final_cut_game/setup_the_incredible_adventures_of_van_helsing_-_final_cut_1.1.0b_(b)_(23988)-4.bin"
[...]
Warning: Could not verify output checksum of file Terrains/Nagyerdo/Files.N2PK
[...]
Opening "the_incredible_adventures_of_van_helsing_final_cut_game/setup_the_incredible_adventures_of_van_helsing_-_final_cut_1.1.0b_(b)_(23988)-5.bin"
[...]
Done with 5 warnings.
```

I verified the md5sums using lgogdownloader and contacted GOG about it. They then confirmed that the md5sums I'd verified match the ones they tested before releasing, so it'd probably be a good idea to identify whether this an edge case that innoextract isn't handling properly or a flaw in that installer which didn't show up as a problem in their testing.

**Comment by dscharrer** [comment]
Hi,

this warning means that innoextract could not calculate the checksum, not that the checksum did not match. This can happen when the GOG Galaxy file parts are stored in a different order from the extracted file because innoextract currently extracts all Inno Setup files in the order they are stored (to minimize seeking in the input file) and calculates the MD5 checksums for files reconstructed from GOG Galaxy file parts while extracting. If the order doesn't match, the output checksum will not be valid and can't be used.

There are ways of fixing this, I just haven't come across a GOG Galaxy installer where the order didn't match before. Have you seen this with other games besides "The Incredible Adventures of Van Helsing - Final Cut"?

This MD5 checksum for the reconstructed files is also only needed for verifying that innoextract reconstructed the file correctly. The compressed parts have their individual SHA-1 checksums like any "normal" file in Inno Setup installers so data corruption will still be reported (as an error with `--test`).

**Comment by ssokolow** [comment]
> There are ways of fixing this, I just haven't come across a GOG Galaxy installer where the order didn't match before. Have you seen this with other games besides "The Incredible Adventures of Van Helsing - Final Cut"?

Not yet, but I have only re-downloaded a small portion of my collection since GOG started doing Galaxy-based installers. (I skip irrelevant updates, such as adding support for cloud saves when I'd probably download the game through Galaxy if I ever changed my mind about using it, and I haven't bought many modern games through GOG.)

> This MD5 checksum for the reconstructed files is also only needed for verifying that innoextract reconstructed the file correctly. The compressed parts have their individual SHA-1 checksums like any "normal" file in Inno Setup installers so data corruption will still be reported (as an error with --test).

I'm not sure I follow. Which of the following is true?

1. The SHA-1 checksums are always in-order, even if the file parts are not. (I'm not familiar with how GOG implemented their Galaxy-based installers. How do the Inno Setup SHA-1 checksums relate to the Galaxy chunking?)
2. You seek around to verify the SHA-1 checksums but don't consider it worth the slow-down of seeking to verify a second set of checksums which should be redundant.

**Comment by dscharrer** [comment]
The SHA-1 checksums are for individual files on the Inno Setup level, so each file parts on the GOG Galaxy level has one SHA-1. Those files can only be stored as one continuous block (except for possibly starting at the end of one .bin file and continuing in the next, but that's still in-order). So (1.) is true.

**Comment by ssokolow** [comment]
OK, so, just to make sure I understand, which of these designs is the case?

1. InnoSetup sees something like `galaxy_chunk1`, `galaxy_chunk2`, `galaxy_chunk3` instead of actual game files and there's a GOG-provided extension DLL it then calls into in order to recombine the chunks into a file.
2. innoextract always verifies the InnoSetup SHA-1 hashes on `galaxy_chunk1`, `galaxy_chunk2`, `galaxy_chunk3`, which inherently must be extractable in a linear fashion.
3. It may not be possible to verify the hashes hashes on the recombined output files without making a second pass over them if the chunks build them in a non-linear fashion. (Something which would fit in with what I heard about Galaxy chunks being intended to support some degree of incremental updating, making them more like primitive binary patches.)
4. The purpose of `Warning: Could not verify output checksum` is to catch bugs in innoextract's Galaxy reassembly code which could cause correct InnoSetup SHA-1 hashes to produce incorrect reassembled files.

If that's the case, the fact that InnoSetup has SHA-1 hashes for all the parts surprises me, given that GOG previously found rebuilding the installers to be enough of a bother that they experimented with integrating an UnRAR DLL and using RAR as the format for the `.bin` files.

(The only other design I can imagine would have Galaxy chunking up the InnoSetup data stream, which makes no sense for a variety of reasons.)

**Comment by dscharrer** [comment]
innoextract 1.8 has been released

It will in some cases reorder the file parts so that the output checksum can be calculated. If the file parts could not be reordered, the extracted file is read back to calculate the checksum when extracting. When not extracting (--test) there is no warning if the checksum could not be calculated.

**Comment by ssokolow** [comment]
> If the file parts could not be reordered, the extracted file is read back to calculate the checksum when extracting. When not extracting (--test) there is no warning if the checksum could not be calculated.

Is there any intermediate option which will do whatever is necessary to calculate the checksum, but delete what's been extracted as soon as the calculation is finished to minimize the amount of free disk space needed?

I'm trying to incorporate innoextract into a little script named `verify_files.py` which recursively walks a tree of folders and eagerly throws warnings for any files it can't be certain are OK. (eg. formats without internal checksums are guaranteed to throw warnings every time.) The intent being to eagerly archive updates to GOG games to dvdisaster-augmented archival-quality DVD+R without having to try installing each one first.

**Comment by dscharrer** [comment]
I'm not sure if it's worth adding something like that as the SHA1 checksums of the individual parts are always verified with --test, only the MD5 checksum of the reconstructed file is not guaranteed to be checked. I think existing behavior should be enough if you want to check for data integrity.

On the other hand, --test with the GOG + multi-part RAR installers already needs temporary files.

**Comment by ssokolow** [comment]
Fair enough. Thanks. :)
