### ISSUE TITLE
-I [ --include ] option doesn't produce error if no matching files found

### ISSUE THREAD

**Issue by bam80** [dscharrer/innoextract#84]
```
$ innoextract Setup-00068-Another_World-PCDOS.exe -Ikjgh
Extracting "Another World" - setup data version 5.3.10
Done.
$ echo $?
0

**Comment by dscharrer** [comment]
I think the current behavior is ok - it extracted all the files you asked it to. You wouldn't expect the program to fail without `-I` when giving it an *empty* installer. Also other tools (for example rsync) also behave this way.
