### ISSUE TITLE
Error on extracting 2.0.18 Inno Setup file with ISX

### ISSUE THREAD

**Issue by ali-hardan** [dscharrer/innoextract#85]
~~~
$ innoextract syberia_sp3.exe
Warning: Unexpected setup data version: 2.0.18
Warning: Unexpected Install Mode value: 117
Warning: Unexpected Uninstall Log Mode value: 101
Warning: Unexpected Uninstall Style value: 59
Warning: Unexpected Auto Boolean value: 13
Warning: Unexpected Auto Boolean value: 28
Stream error while parsing setup headers!
 ├─ detected setup version: 2.0.18
 └─ error reason: basic_ios::clear: iostream error
If you are sure the setup file is not corrupted, consider
filing a bug report at http://innoextract.constexpr.org/issues
Done with 1 error and 6 warnings.
~~~

I got installer from: https://www.fileplanet.com/archive/p-49644/Syberia-Patch-SP3

Tested on  innoextract `1.7` and `1.8-dev-2019-01-13`

**Comment by ali-hardan** [comment]
I can extract it using:

    $ wine ./cmdTotal.exe InstExpl.wcx x "syberia_sp3.exe" "/path/to/extract/"

**Comment by dscharrer** [comment]
The linked installer seems to have been created with an older version of [Martijn Laan's My Inno Setup Extensions](http://web.archive.org/web/20150507221835/http://isx.wintax.nl/). I can't find the source code for that version but will try to RE the installer.

**Comment by vv221** [comment]
Since commit https://github.com/dscharrer/innoextract/commit/4c61bc4da822fc89f2e05bdb2c45e6c4dd7a3673 fixed this issue, should it not be closed?

**Comment by dscharrer** [comment]
innoextract 1.8 has been released with support for older ISX installers.
