### ISSUE TITLE
Release package?

### ISSUE THREAD

**Issue by rfht** [dscharrer/innoextract#87]
Hi,

I maintain the port on OpenBSD and very much appreciate innoextract, especially the fact that releases are made available as stable packages on `https://constexpr.org/innoextract`. The main use case is GOG.com game downloads because there is no working client like Galaxy or Lutris on OpenBSD. Unfortunately, some GOG packages don't extract with innoextract 1.7 anymore (as referenced in the commit 38ae68f that fixes it).

Is there anything holding back a release with this fix? Using the releases from `https://constexpr.org/innoextract` is the best source for the OpenBSD port because GitHub changes their formula for autogenerated tarballs regularly, breaking our port's SHA256 checking.

Thanks!

**Comment by dscharrer** [comment]
I'll get to innoextract 1.8 soon, just have a lot of things to catch up on.

**Comment by dscharrer** [comment]
innoextract 1.8 has been released.
