### ISSUE TITLE
Not a supported Inno Setup installer

### ISSUE THREAD

**Issue by cup** [dscharrer/innoextract#89]
Using this file

https://julialang-s3.julialang.org/bin/winnt/x64/1.1/julia-1.1.1-win64.exe

I get this result:

~~~
> innoextract.exe julia-1.1.1-win64.exe
Not a supported Inno Setup installer!
Done with 1 error.
~~~

**Comment by dscharrer** [comment]
`innoextract` can only extract installers that were created with Inno Setup. Like the error message says, this is not one of them.
