### ISSUE TITLE
Lenovo IdePad L340

### ISSUE THREAD

**Issue by HBartolin** [dscharrer/innoextract#96]
Hi,

I get this error:

innoextract 1.7
Extracts installers created by Inno Setup 1.2.10 to 5.6.0

Warning: Unexpected setup data version: 6.0.0 (unicode)
Warning: Unexpected Auto Boolean value: 10
Stream error while parsing setup headers!
 ├─ detected setup version: 6.0.0 (unicode)
 └─ error reason: basic_ios::clear: iostream error

**Comment by dscharrer** [comment]
http://constexpr.org/innoextract/#news
