### ISSUE TITLE
error during extracting

### ISSUE THREAD

**Issue by ExaFlop1** [dscharrer/innoextract#98]
innoextract.exe -e "D:\Photo Studio\zpsx_en.exe" -d "temp" -m -s

Warning: Unexpected trailing byte in UTF-16 string.
Warning: Unexpected data while converting from UTF-16LE to UTF-8.
Warning: Unexpected trailing byte in UTF-16 string.
Warning: Unexpected data while converting from UTF-16LE to UTF-8.
Warning: Unexpected trailing byte in UTF-16 string.
Warning: Unexpected data while converting from UTF-16LE to UTF-8.
Warning: Unexpected trailing byte in UTF-16 string.
Warning: Unexpected data while converting from UTF-16LE to UTF-8.
Warning: Unexpected trailing byte in UTF-16 string.
Warning: Unexpected data while converting from UTF-16LE to UTF-8.
Warning: Unexpected trailing byte in UTF-16 string.
Warning: Unexpected data while converting from UTF-16LE to UTF-8.
Warning: Unexpected trailing byte in UTF-16 string.
Warning: Unexpected data while converting from UTF-16LE to UTF-8.
Warning: Unexpected trailing byte in UTF-16 string.
Warning: Unexpected data while converting from UTF-16LE to UTF-8.
Warning: Unexpected trailing byte in UTF-16 string.
Warning: Unexpected data while converting from UTF-16LE to UTF-8.
Warning: Unexpected trailing byte in UTF-16 string.
Warning: Unexpected data while converting from UTF-16LE to UTF-8.
Stream error while parsing setup headers!
 ├─ detected setup version: 5.5.7 (unicode)
 └─ error reason: basic_ios::clear: iostream error

**Comment by dscharrer** [comment]
Which version of innoextract are you using? You can check using `innoextract --version`.

Is this installer publicly available somewhere?

**Comment by ExaFlop1** [comment]
Latest - 1.8

**Comment by dscharrer** [comment]
Without the setup file in question, there is nothing I can do about this.
